# Generated by Django 5.0 on 2023-12-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('number_of_rooms', models.IntegerField()),
                ('area', models.IntegerField()),
                ('max_number_of_people', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=255)),
                ('price_of_day', models.IntegerField()),
                ('number_of_room', models.IntegerField()),
                ('type', models.CharField(choices=[('Single', 'One person'), ('Double', 'Two person'), ('Apartament', 'More person')], max_length=15)),
                ('availability', models.BooleanField(choices=[('Yes', 'Accessible'), ('No', 'Inaccessible')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('adress', models.TextField(max_length=255)),
                ('phone_number', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('max_number_of_people', models.IntegerField(default=4)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('begin_reservation', models.DateTimeField()),
                ('end_reservation', models.DateTimeField()),
                ('number_of_people', models.IntegerField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('Canceled', 'Canceled')], max_length=15)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.user')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rate', models.CharField(choices=[('1/5', 'Very bad'), ('2/5', ' Bad'), ('3/5', 'Middling'), ('4/5', 'Good'), ('5/5', 'Very Good')], max_length=10)),
                ('date_of_issue', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.room')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.user')),
            ],
        ),
    ]
