# Generated by Django 5.0 on 2023-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rate',
            field=models.CharField(choices=[('1/5', 'Very bad'), ('2/5', ' Bad'), ('3/5', 'Middling'), ('4/5', 'Good'), ('5/5', 'Very Good')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('Canceled', 'Canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(choices=[('Yes', 'Accessible'), ('No', 'Inaccessible')]),
        ),
    ]
