# Generated by Django 5.0 on 2023-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0002_alter_opinion_rate_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Single', 'One person'), ('Double', 'Two person'), ('Apartament', 'More person')], max_length=25),
        ),
    ]
