# Generated by Django 5.0 on 2024-01-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0005_alter_opinion_rate_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
