# Generated by Django 5.0 on 2024-01-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0006_room_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rating',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date_of_issue',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')]),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='begin_reservation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_reservation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Waiting', 'Waiting'), ('Canceled', 'Canceled')], default='Waiting', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Accessible', 'Accessible'), ('Inaccessible', 'Inaccessible')], max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Apartament', 'Apartament')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transport',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
