# Generated by Django 5.0 on 2024-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0007_remove_room_rating_alter_opinion_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
