# Generated by Django 5.0 on 2024-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0009_alter_reservation_number_of_people_alter_room_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='max_number_of_people',
            new_name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='price',
        ),
        migrations.AddField(
            model_name='transport',
            name='ending_location',
            field=models.CharField(default='Room', max_length=240),
        ),
        migrations.AddField(
            model_name='transport',
            name='starting_location',
            field=models.CharField(default='Dworzec', max_length=255),
        ),
    ]
