# Generated by Django 5.0 on 2024-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0011_alter_opinion_review_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'begin_reservation', 'end_reservation')},
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
