# Generated by Django 5.0 on 2024-01-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0012_alter_opinion_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wynajem.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='reserved_dates',
            field=models.ManyToManyField(related_name='reserved_rooms', through='wynajem.RoomReservation', to='wynajem.reservation'),
        ),
    ]
