# Generated by Django 5.0 on 2024-01-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wynajem', '0013_roomreservation_room_reserved_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reserved_dates',
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
